language: objective-c
osx_image: xcode8
script:
- xcodebuild test -project RFISO8601DateTime.xcodeproj -scheme RFISO8601DateTimeTests
  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO  -destination 'platform=iOS Simulator,name=iPhone
  7' | xcpretty
- pod lib lint --quick
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive RFISO8601DateTime
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: Ltftl9EwrbjyO0u9ehSHQtwIZjni5KcUCXC6AO9q2Nrd4+xbhY3H6w4vfuz6AoavcDf92TiwDd4NIiImoPATDgxbvfP/eeWY3sFOjwFSoW6S7b30739Pem8Rw9vEy7I/Co55qfxomvxJFKfWbgWQHiY+LmPykVgI1XR2M1IHU2zT4oV4//5GbKPV0iWc6ir/pSQACdAsMhea/AMs7PbdbupjvZ9xeIuPAHnkEeNsO5WtdvG2+YZpNTEouABU+amR5noqjK0te0UnjRdnhN4MSbP4JEGZMEAgwiYkteILwt/e4MqHuuH3d66Vr7P7lriUW1dv60g1sEcfKxYzw5ZziiOUBBy+t1zTXJ1Z6JJQS7WQsuABsj3//xpaLsSG8Wk/C5UFZjTS4OLf0c0h9/MC60LOtrNp5xYmx6HeIpo80GUoGk7njDtBS0ycVxN2gjGqwJIwGVklodhJusmTzrXZ5A3MCexg6Pm7RD1td3yngptRqZlcje56VTH0wV+lWh3EMass8e+tSx/iO8FuSgKG4eE2agdpVvPT6F/wcsrlLn6R19nubNRMFY8io/kuytR+52gE2o5ibUGI6uB/sbqwkhDaR1bVSyH5/A92LjdDNsdt2/HJ1Dq81xnXNjHEWZss2zj60ZyEYIvneMVxIRBlQORlh6Z+BBq6FJmVEkfY+pw=
  file: RFISO8601DateTime.framework.zip
  skip_cleanup: true
  on:
    repo: readefries/RFISO8601DateTime
    tags: true
