language: objective-c
osx_image: xcode7.3

before_install:
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean build -project RFISO8601DateTime.xcodeproj -scheme 'RFISO8601DateTime' -sdk iphonesimulator9.2 ONLY_ACTIVE_ARCH=NO

